/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  if (!is_admin) {
    return NextResponse.json(
      { error: 'Admin access required' },
      { status: 403 }
    );
  }
  
  try {
    const { 
      name, 
      slug, 
      description, 
      price, 
      billing_period, 
      stripe_price_id, 
      features, 
      limits, 
      display_order, 
      enabled, 
      is_featured, 
      trial_days 
    } = await request.json();
    
    // Validate required fields
    if (!name || !name.trim()) {
      return NextResponse.json(
        { error: 'Name is required' },
        { status: 400 }
      );
    }
    
    if (!slug || !slug.trim()) {
      return NextResponse.json(
        { error: 'Slug is required' },
        { status: 400 }
      );
    }
    
    // Validate slug format (lowercase alphanumeric with dashes)
    const slugRegex = /^[a-z0-9-]+$/;
    if (!slugRegex.test(slug)) {
      return NextResponse.json(
        { error: 'Slug must be lowercase alphanumeric with dashes only' },
        { status: 400 }
      );
    }
    
    if (price === undefined || price === null) {
      return NextResponse.json(
        { error: 'Price is required' },
        { status: 400 }
      );
    }
    
    // Check if slug already exists
    const existingQuery = 'SELECT id FROM subscription_tiers WHERE slug = ?';
    const existingResult = await db_query(db, existingQuery, [slug]);
    
    if (existingResult.length > 0) {
      return NextResponse.json(
        { error: 'A tier with this slug already exists' },
        { status: 400 }
      );
    }
    
    // Generate UUID
    const id = crypto.randomUUID();
    
    // Set defaults
    const tierData = {
      id,
      name: name.trim(),
      slug: slug.trim(),
      description: description || null,
      price: parseFloat(price) || 0,
      billing_period: billing_period || 'monthly',
      stripe_price_id: stripe_price_id || null,
      features: JSON.stringify(features || []),
      limits: JSON.stringify(limits || {}),
      display_order: display_order !== undefined ? parseInt(display_order) : 0,
      enabled: enabled !== false,
      is_featured: is_featured || false,
      trial_days: trial_days !== undefined ? parseInt(trial_days) : 0
    };
    
    // Insert tier
    const insertQuery = `
      INSERT INTO subscription_tiers (
        id, name, slug, description, price, billing_period, stripe_price_id,
        features, limits, display_order, enabled, is_featured, trial_days
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `;
    
    await db_query(db, insertQuery, [
      tierData.id,
      tierData.name,
      tierData.slug,
      tierData.description,
      tierData.price,
      tierData.billing_period,
      tierData.stripe_price_id,
      tierData.features,
      tierData.limits,
      tierData.display_order,
      tierData.enabled,
      tierData.is_featured,
      tierData.trial_days
    ]);
    
    // Return created tier
    return NextResponse.json({
      id: tierData.id,
      name: tierData.name,
      slug: tierData.slug,
      description: tierData.description,
      price: tierData.price,
      billing_period: tierData.billing_period,
      stripe_price_id: tierData.stripe_price_id,
      features: features || [],
      limits: limits || {},
      display_order: tierData.display_order,
      enabled: tierData.enabled,
      is_featured: tierData.is_featured,
      trial_days: tierData.trial_days,
      created_at: new Date().toISOString()
    });
    
  } catch (error) {
    console.error('Tier creation error:', error);
    return NextResponse.json(
      { error: 'Failed to create tier', message: error.message },
      { status: 500 }
    );
  }
}


