/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request, { params }) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  // This is an admin-only endpoint for customer management
  if (!is_admin) {
    return NextResponse.json(
      { error: 'Admin access required' },
      { status: 403 }
    );
  }
  
  try {
    // Get customer ID from query parameter
    const customerId = params.id;
    
    if (!customerId) {
      return NextResponse.json(
        { error: 'Customer ID is required' },
        { status: 400 }
      );
    }
    
    // Validate UUID format
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(customerId)) {
      return NextResponse.json(
        { error: 'Invalid customer ID format' },
        { status: 400 }
      );
    }
    
    // Get customer
    const query = `
      SELECT 
        id, userid, first_name, last_name, email, phone,
        date_of_birth, gender, company_name, vat_number,
        customer_type, status, loyalty_points, loyalty_tier,
        total_spent, total_orders, preferred_language,
        preferred_currency, marketing_consent, newsletter_subscribed,
        notes, tags, metadata, created_at, updated_at, last_login_at
      FROM customers
      WHERE id = ?
    `;
    
    const result = await db_query(db, query, [customerId]);
    
    if (result.length === 0) {
      return NextResponse.json(
        { error: 'Customer not found' },
        { status: 404 }
      );
    }
    
    const customer = result[0];
    
    // Format response
    const response = {
      id: customer.id,
      userid: customer.userid,
      first_name: customer.first_name,
      last_name: customer.last_name,
      email: customer.email,
      phone: customer.phone,
      date_of_birth: customer.date_of_birth,
      gender: customer.gender,
      company_name: customer.company_name,
      vat_number: customer.vat_number,
      customer_type: customer.customer_type,
      status: customer.status,
      loyalty_points: parseInt(customer.loyalty_points),
      loyalty_tier: customer.loyalty_tier,
      total_spent: parseFloat(customer.total_spent),
      total_orders: parseInt(customer.total_orders),
      preferred_language: customer.preferred_language,
      preferred_currency: customer.preferred_currency,
      marketing_consent: customer.marketing_consent,
      newsletter_subscribed: customer.newsletter_subscribed,
      notes: customer.notes,
      tags: customer.tags || [],
      metadata: customer.metadata || {},
      created_at: customer.created_at,
      updated_at: customer.updated_at,
      last_login_at: customer.last_login_at
    };
    
    return NextResponse.json(response);
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to retrieve customer', message: error.message },
      { status: 500 }
    );
  }
}


