/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    const slug = searchParams.get('slug');
    
    if (!id && !slug) {
      return NextResponse.json(
        { error: 'Either id or slug is required' },
        { status: 400 }
      );
    }
    
    let query;
    let params;
    
    if (id) {
      query = 'SELECT * FROM subscription_tiers WHERE id = ?';
      params = [id];
    } else {
      query = 'SELECT * FROM subscription_tiers WHERE slug = ?';
      params = [slug];
    }
    
    const result = await db_query(db, query, params);
    
    if (result.length === 0) {
      return NextResponse.json(
        { error: 'Tier not found' },
        { status: 404 }
      );
    }
    
    const tier = result[0];
    
    // Parse JSON fields
    return NextResponse.json({
      id: tier.id,
      name: tier.name,
      slug: tier.slug,
      description: tier.description,
      price: parseFloat(tier.price) || 0,
      billing_period: tier.billing_period,
      stripe_price_id: tier.stripe_price_id,
      features: typeof tier.features === 'string' ? JSON.parse(tier.features) : (tier.features || []),
      limits: typeof tier.limits === 'string' ? JSON.parse(tier.limits) : (tier.limits || {}),
      display_order: tier.display_order,
      enabled: tier.enabled === true || tier.enabled === 1,
      is_featured: tier.is_featured === true || tier.is_featured === 1,
      trial_days: tier.trial_days,
      created_at: tier.created_at
    });
    
  } catch (error) {
    console.error('Tier get error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch tier', message: error.message },
      { status: 500 }
    );
  }
}


