/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
  
  try {
    const { searchParams } = new URL(request.url);
    const enabled = searchParams.get('enabled');
    const sort = searchParams.get('sort') || 'display_order';
    const order = searchParams.get('order') || 'asc';
    
    // Build query
    let query = 'SELECT * FROM subscription_tiers';
    const params = [];
    const conditions = [];
    
    // For non-admin users, only show enabled tiers
    if (!is_admin) {
      conditions.push('enabled = ?');
      params.push(true);
    } else if (enabled !== null) {
      // Admin can filter by enabled status
      conditions.push('enabled = ?');
      params.push(enabled === 'true');
    }
    
    if (conditions.length > 0) {
      query += ' WHERE ' + conditions.join(' AND ');
    }
    
    // Validate sort column
    const validSortColumns = ['name', 'price', 'display_order', 'created_at'];
    const sortColumn = validSortColumns.includes(sort) ? sort : 'display_order';
    const sortOrder = order.toLowerCase() === 'desc' ? 'DESC' : 'ASC';
    
    query += ` ORDER BY ${sortColumn} ${sortOrder}`;
    
    const result = await db_query(db, query, params);
    
    // Parse JSON fields
    const tiers = result.map(tier => ({
      ...tier,
      features: typeof tier.features === 'string' ? JSON.parse(tier.features) : (tier.features || []),
      limits: typeof tier.limits === 'string' ? JSON.parse(tier.limits) : (tier.limits || {}),
      price: parseFloat(tier.price) || 0,
      enabled: tier.enabled === true || tier.enabled === 1,
      is_featured: tier.is_featured === true || tier.is_featured === 1
    }));
    
    return NextResponse.json({
      data: tiers
    });
    
  } catch (error) {
    console.error('Tiers list error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch tiers', message: error.message },
      { status: 500 }
    );
  }
}


