/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '20');
    const search = searchParams.get('search') || '';
    const department = searchParams.get('department') || '';
    const status = searchParams.get('status') || '';
    const employment_type = searchParams.get('employment_type') || '';
    const sort_by = searchParams.get('sort_by') || 'last_name';
    const sort_order = (searchParams.get('sort_order') || 'ASC').toUpperCase();
    
    if (sort_order !== 'ASC' && sort_order !== 'DESC') {
      return NextResponse.json(
        { error: 'Invalid sort order. Must be ASC or DESC' },
        { status: 400 }
      );
    }
    
    const conditions = [];
    const values = [];
    
    if (search) {
      conditions.push(`(
        LOWER(first_name) LIKE LOWER(?) OR 
        LOWER(last_name) LIKE LOWER(?) OR 
        LOWER(email) LIKE LOWER(?)
      )`);
      const searchPattern = `%${search}%`;
      values.push(searchPattern, searchPattern, searchPattern);
    }
    
    if (department) {
      conditions.push('department = ?');
      values.push(department);
    }
    
    if (status) {
      conditions.push('status = ?');
      values.push(status);
    }
    
    if (employment_type) {
      conditions.push('employment_type = ?');
      values.push(employment_type);
    }
    
    const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
    
    // Get total count
    const countQuery = `SELECT COUNT(*) as count FROM employees ${whereClause}`;
    const countResult = await db_query(db, countQuery, values);
    const total = parseInt(countResult[0].count);
    
    const offset = (page - 1) * limit;
    const pages = Math.ceil(total / limit);
    
    const allowedSortFields = ['first_name', 'last_name', 'email', 'department', 'job_title', 'hire_date', 'created_at'];
    const finalSortBy = allowedSortFields.includes(sort_by) ? sort_by : 'last_name';
    
    const dataQuery = `
      SELECT 
        id, userid, employee_number, first_name, last_name, email, phone,
        avatar_url, job_title, department, manager_id, hire_date,
        employment_type, status, location, timezone, skills, bio,
        created_at, updated_at
      FROM employees 
      ${whereClause}
      ORDER BY ${finalSortBy} ${sort_order}
      LIMIT ? OFFSET ?
    `;
    
    const dataResult = await db_query(db, dataQuery, [...values, limit, offset]);
    
    const employees = dataResult.map(emp => ({
      id: emp.id,
      userid: emp.userid,
      employee_number: emp.employee_number,
      first_name: emp.first_name,
      last_name: emp.last_name,
      full_name: `${emp.first_name} ${emp.last_name}`,
      email: emp.email,
      phone: emp.phone,
      avatar_url: emp.avatar_url,
      job_title: emp.job_title,
      department: emp.department,
      manager_id: emp.manager_id,
      hire_date: emp.hire_date,
      employment_type: emp.employment_type,
      status: emp.status,
      location: emp.location,
      timezone: emp.timezone,
      skills: emp.skills || [],
      bio: emp.bio,
      created_at: emp.created_at,
      updated_at: emp.updated_at
    }));
    
    return NextResponse.json({
      data: employees,
      pagination: {
        total,
        pages,
        current: page,
        limit
      }
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to list employees', message: error.message },
      { status: 500 }
    );
  }
}


