/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const project_id = searchParams.get('project_id');
    const status = searchParams.get('status') || '';
    const priority = searchParams.get('priority') || '';
    const assignee_id = searchParams.get('assignee_id') || '';
    const search = searchParams.get('search') || '';
    const sort_by = searchParams.get('sort_by') || 'position';
    const sort_order = (searchParams.get('sort_order') || 'ASC').toUpperCase();
    
    if (!project_id) {
      return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
    }
    
    const conditions = ['t.project_id = ?'];
    const values = [project_id];
    
    if (status) {
      conditions.push('t.status = ?');
      values.push(status);
    }
    
    if (priority) {
      conditions.push('t.priority = ?');
      values.push(priority);
    }
    
    if (assignee_id) {
      conditions.push('t.assignee_id = ?');
      values.push(assignee_id);
    }
    
    if (search) {
      conditions.push('(LOWER(t.title) LIKE LOWER(?) OR LOWER(t.description) LIKE LOWER(?))');
      values.push(`%${search}%`, `%${search}%`);
    }
    
    const whereClause = `WHERE ${conditions.join(' AND ')}`;
    
    const allowedSortFields = ['position', 'title', 'status', 'priority', 'due_date', 'created_at', 'updated_at'];
    const finalSortBy = allowedSortFields.includes(sort_by) ? sort_by : 'position';
    
    const query = `
      SELECT 
        t.*,
        a.first_name as assignee_first_name,
        a.last_name as assignee_last_name,
        a.avatar_url as assignee_avatar
      FROM tasks t
      LEFT JOIN employees a ON t.assignee_id = a.id
      ${whereClause}
      ORDER BY t.status, t.${finalSortBy} ${sort_order}
    `;
    
    const result = await db_query(db, query, values);
    
    const tasks = result.map(t => ({
      id: t.id,
      project_id: t.project_id,
      parent_task_id: t.parent_task_id,
      title: t.title,
      description: t.description,
      status: t.status,
      priority: t.priority,
      assignee_id: t.assignee_id,
      assignee: t.assignee_id ? {
        id: t.assignee_id,
        name: `${t.assignee_first_name} ${t.assignee_last_name}`,
        avatar_url: t.assignee_avatar
      } : null,
      reporter_id: t.reporter_id,
      due_date: t.due_date,
      start_date: t.start_date,
      completed_at: t.completed_at,
      estimated_hours: t.estimated_hours ? parseFloat(t.estimated_hours) : null,
      actual_hours: parseFloat(t.actual_hours) || 0,
      position: parseInt(t.position) || 0,
      labels: t.labels || [],
      attachments: t.attachments || [],
      checklist: t.checklist || [],
      comment_count: parseInt(t.comment_count) || 0,
      metadata: t.metadata || {},
      created_at: t.created_at,
      updated_at: t.updated_at
    }));
    
    return NextResponse.json({ data: tasks });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to list tasks', message: error.message },
      { status: 500 }
    );
  }
}


