/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const body = await request.json();
    const { project_id, employee_id, role } = body;
    
    if (!project_id || !employee_id) {
      return NextResponse.json({ error: 'Project ID and employee ID are required' }, { status: 400 });
    }
    
    // Get current user's employee ID
    const empQuery = `SELECT id FROM employees WHERE userid = ?`;
    const empResult = await db_query(db, empQuery, [user_id]);
    const currentEmployeeId = empResult.length > 0 ? empResult[0].id : null;
    
    // Check if current user is project owner or admin
    if (!is_admin) {
      const authQuery = `
        SELECT role FROM project_members 
        WHERE project_id = ? AND employee_id = ? AND role IN ('owner', 'admin')
      `;
      const authResult = await db_query(db, authQuery, [project_id, currentEmployeeId]);
      
      if (authResult.length === 0) {
        return NextResponse.json({ error: 'Not authorized to add members' }, { status: 403 });
      }
    }
    
    // Check if already a member
    const existingQuery = `SELECT id FROM project_members WHERE project_id = ? AND employee_id = ?`;
    const existing = await db_query(db, existingQuery, [project_id, employee_id]);
    
    if (existing.length > 0) {
      return NextResponse.json({ error: 'Already a project member' }, { status: 400 });
    }
    
    // Validate role
    const validRoles = ['admin', 'member', 'viewer'];
    const memberRole = validRoles.includes(role) ? role : 'member';
    
    const memberId = crypto.randomUUID();
    
    const insertQuery = `
      INSERT INTO project_members (id, project_id, employee_id, role, invited_by)
      VALUES (?, ?, ?, ?, ?)
      RETURNING *
    `;
    
    const result = await db_query(db, insertQuery, [
      memberId,
      project_id,
      employee_id,
      memberRole,
      currentEmployeeId
    ]);
    
    const member = result[0];
    
    // Get employee details
    const employeeQuery = `SELECT first_name, last_name, email, avatar_url FROM employees WHERE id = ?`;
    const employeeResult = await db_query(db, employeeQuery, [employee_id]);
    const emp = employeeResult[0];
    
    return NextResponse.json({
      id: member.id,
      project_id: member.project_id,
      employee_id: member.employee_id,
      role: member.role,
      employee: emp ? {
        id: employee_id,
        name: `${emp.first_name} ${emp.last_name}`,
        email: emp.email,
        avatar_url: emp.avatar_url
      } : null,
      joined_at: member.joined_at
    }, { status: 201 });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to add member', message: error.message },
      { status: 500 }
    );
  }
}


