/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json({ error: 'Task ID is required' }, { status: 400 });
    }
    
    // Get task
    const taskQuery = `SELECT * FROM tasks WHERE id = ?`;
    const taskResult = await db_query(db, taskQuery, [id]);
    
    if (taskResult.length === 0) {
      return NextResponse.json({ error: 'Task not found' }, { status: 404 });
    }
    
    const task = taskResult[0];
    const wasCompleted = task.status === 'done';
    
    // Delete subtasks first
    const subtaskIds = await db_query(db, `SELECT id FROM tasks WHERE parent_task_id = ?`, [id]);
    for (const subtask of subtaskIds) {
      await db_query(db, `DELETE FROM task_comments WHERE task_id = ?`, [subtask.id]);
      await db_query(db, `DELETE FROM tasks WHERE id = ?`, [subtask.id]);
    }
    
    // Delete comments
    await db_query(db, `DELETE FROM task_comments WHERE task_id = ?`, [id]);
    
    // Delete task
    await db_query(db, `DELETE FROM tasks WHERE id = ?`, [id]);
    
    // Update project counts
    const completedDelta = wasCompleted ? -1 : 0;
    await db_query(db, `
      UPDATE projects 
      SET task_count = task_count - 1,
          completed_task_count = completed_task_count + ?,
          progress = CASE WHEN task_count > 1 THEN ((completed_task_count + ?) * 100 / (task_count - 1)) ELSE 0 END,
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `, [completedDelta, completedDelta, task.project_id]);
    
    return NextResponse.json({ success: true });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to delete task', message: error.message },
      { status: 500 }
    );
  }
}


