/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const body = await request.json();
    const { task_id, content, parent_comment_id } = body;
    
    if (!task_id || !content || !content.trim()) {
      return NextResponse.json({ error: 'Task ID and content are required' }, { status: 400 });
    }
    
    // Get author employee ID
    const empQuery = `SELECT id, first_name, last_name, avatar_url FROM employees WHERE userid = ?`;
    const empResult = await db_query(db, empQuery, [user_id]);
    
    if (empResult.length === 0) {
      return NextResponse.json({ error: 'Employee profile required' }, { status: 403 });
    }
    
    const employee = empResult[0];
    
    // Extract mentions from content (@username pattern)
    const mentionRegex = /@(\w+)/g;
    const mentions = [];
    let match;
    while ((match = mentionRegex.exec(content)) !== null) {
      mentions.push(match[1]);
    }
    
    const commentId = crypto.randomUUID();
    
    const insertQuery = `
      INSERT INTO task_comments (id, task_id, author_id, content, parent_comment_id, mentions)
      VALUES (?, ?, ?, ?, ?, ?)
      RETURNING *
    `;
    
    const result = await db_query(db, insertQuery, [
      commentId,
      task_id,
      employee.id,
      content.trim(),
      parent_comment_id || null,
      JSON.stringify(mentions)
    ]);
    
    const comment = result[0];
    
    // Update task comment count
    await db_query(db, `UPDATE tasks SET comment_count = comment_count + 1 WHERE id = ?`, [task_id]);
    
    return NextResponse.json({
      id: comment.id,
      task_id: comment.task_id,
      author: {
        id: employee.id,
        name: `${employee.first_name} ${employee.last_name}`,
        avatar_url: employee.avatar_url
      },
      content: comment.content,
      parent_comment_id: comment.parent_comment_id,
      mentions,
      created_at: comment.created_at
    }, { status: 201 });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to create comment', message: error.message },
      { status: 500 }
    );
  }
}


