/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json({ error: 'Member ID is required' }, { status: 400 });
    }
    
    // Get member
    const memberQuery = `SELECT * FROM project_members WHERE id = ?`;
    const memberResult = await db_query(db, memberQuery, [id]);
    
    if (memberResult.length === 0) {
      return NextResponse.json({ error: 'Member not found' }, { status: 404 });
    }
    
    const member = memberResult[0];
    
    // Cannot remove owner
    if (member.role === 'owner') {
      return NextResponse.json({ error: 'Cannot remove project owner' }, { status: 403 });
    }
    
    // Get current user's employee ID
    const empQuery = `SELECT id FROM employees WHERE userid = ?`;
    const empResult = await db_query(db, empQuery, [user_id]);
    const currentEmployeeId = empResult.length > 0 ? empResult[0].id : null;
    
    // Check authorization - can remove self, or must be owner/admin
    const isSelf = member.employee_id === currentEmployeeId;
    
    if (!is_admin && !isSelf) {
      const authQuery = `
        SELECT role FROM project_members 
        WHERE project_id = ? AND employee_id = ? AND role IN ('owner', 'admin')
      `;
      const authResult = await db_query(db, authQuery, [member.project_id, currentEmployeeId]);
      
      if (authResult.length === 0) {
        return NextResponse.json({ error: 'Not authorized to remove members' }, { status: 403 });
      }
    }
    
    // Remove member
    await db_query(db, `DELETE FROM project_members WHERE id = ?`, [id]);
    
    return NextResponse.json({ success: true });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to remove member', message: error.message },
      { status: 500 }
    );
  }
}


