/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Get customer_id for the authenticated user
    const customerResult = await db_query(db, 'SELECT id FROM customers WHERE userid = ?', [user_id]);
    if (customerResult.length === 0) {
      return NextResponse.json({ error: 'Customer profile not found' }, { status: 404 });
    }
    const customer_id = customerResult[0].id;
    
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'Invoice ID is required' },
        { status: 400 }
      );
    }
    
    // Check ownership and status, also get time_entry_ids for timetracking integration
    const checkQuery = `SELECT status, time_entry_ids FROM invoices WHERE id = ? AND customer_id = ?`;
    const existing = await db_query(db, checkQuery, [id, customer_id]);
    
    if (existing.length === 0) {
      return NextResponse.json(
        { error: 'Invoice not found' },
        { status: 404 }
      );
    }
    
    if (existing[0].status === 'paid') {
      return NextResponse.json(
        { error: 'Cannot delete a paid invoice' },
        { status: 400 }
      );
    }
    
    // Get time entry IDs associated with this invoice for timetracking integration
    const timeEntryIds = existing[0].time_entry_ids || [];
    
    // If there are linked time entries, mark them as available for billing again
    if (timeEntryIds.length > 0) {
      const placeholders = timeEntryIds.map(() => '?').join(',');
      await db_query(
        db,
        `UPDATE time_entries SET is_billable = true WHERE id IN (${placeholders}) AND userid = ?`,
        [...timeEntryIds, user_id]
      );
    }
    
    const query = `DELETE FROM invoices WHERE id = ? AND customer_id = ?`;
    await db_query(db, query, [id, customer_id]);
    
    return NextResponse.json({ 
      message: 'Invoice deleted successfully',
      released_time_entries: timeEntryIds.length
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to delete invoice', message: error.message },
      { status: 500 }
    );
  }
}


