/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  if (!is_admin) {
    return NextResponse.json(
      { error: 'Admin access required' },
      { status: 403 }
    );
  }
  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'Tier ID is required' },
        { status: 400 }
      );
    }
    
    // Check if tier exists
    const existingQuery = 'SELECT * FROM subscription_tiers WHERE id = ?';
    const existingResult = await db_query(db, existingQuery, [id]);
    
    if (existingResult.length === 0) {
      return NextResponse.json(
        { error: 'Tier not found' },
        { status: 404 }
      );
    }
    
    const existingTier = existingResult[0];
    
    const body = await request.json();
    const { 
      name, 
      slug, 
      description, 
      price, 
      billing_period, 
      stripe_price_id, 
      features, 
      limits, 
      display_order, 
      enabled, 
      is_featured, 
      trial_days 
    } = body;
    
    // If slug is being changed, check for uniqueness
    if (slug && slug !== existingTier.slug) {
      const slugRegex = /^[a-z0-9-]+$/;
      if (!slugRegex.test(slug)) {
        return NextResponse.json(
          { error: 'Slug must be lowercase alphanumeric with dashes only' },
          { status: 400 }
        );
      }
      
      const slugCheckQuery = 'SELECT id FROM subscription_tiers WHERE slug = ? AND id != ?';
      const slugCheckResult = await db_query(db, slugCheckQuery, [slug, id]);
      
      if (slugCheckResult.length > 0) {
        return NextResponse.json(
          { error: 'A tier with this slug already exists' },
          { status: 400 }
        );
      }
    }
    
    // Build update query dynamically
    const updates = [];
    const params = [];
    
    if (name !== undefined) {
      updates.push('name = ?');
      params.push(name.trim());
    }
    if (slug !== undefined) {
      updates.push('slug = ?');
      params.push(slug.trim());
    }
    if (description !== undefined) {
      updates.push('description = ?');
      params.push(description);
    }
    if (price !== undefined) {
      updates.push('price = ?');
      params.push(parseFloat(price) || 0);
    }
    if (billing_period !== undefined) {
      updates.push('billing_period = ?');
      params.push(billing_period);
    }
    if (stripe_price_id !== undefined) {
      updates.push('stripe_price_id = ?');
      params.push(stripe_price_id);
    }
    if (features !== undefined) {
      updates.push('features = ?');
      params.push(JSON.stringify(features));
    }
    if (limits !== undefined) {
      updates.push('limits = ?');
      params.push(JSON.stringify(limits));
    }
    if (display_order !== undefined) {
      updates.push('display_order = ?');
      params.push(parseInt(display_order));
    }
    if (enabled !== undefined) {
      updates.push('enabled = ?');
      params.push(enabled);
    }
    if (is_featured !== undefined) {
      updates.push('is_featured = ?');
      params.push(is_featured);
    }
    if (trial_days !== undefined) {
      updates.push('trial_days = ?');
      params.push(parseInt(trial_days));
    }
    
    if (updates.length === 0) {
      return NextResponse.json(
        { error: 'No fields to update' },
        { status: 400 }
      );
    }
    
    updates.push('updated_at = CURRENT_TIMESTAMP');
    params.push(id);
    
    const updateQuery = `UPDATE subscription_tiers SET ${updates.join(', ')} WHERE id = ?`;
    await db_query(db, updateQuery, params);
    
    // Fetch updated tier
    const updatedResult = await db_query(db, 'SELECT * FROM subscription_tiers WHERE id = ?', [id]);
    const tier = updatedResult[0];
    
    return NextResponse.json({
      id: tier.id,
      name: tier.name,
      slug: tier.slug,
      description: tier.description,
      price: parseFloat(tier.price) || 0,
      billing_period: tier.billing_period,
      stripe_price_id: tier.stripe_price_id,
      features: typeof tier.features === 'string' ? JSON.parse(tier.features) : (tier.features || []),
      limits: typeof tier.limits === 'string' ? JSON.parse(tier.limits) : (tier.limits || {}),
      display_order: tier.display_order,
      enabled: tier.enabled === true || tier.enabled === 1,
      is_featured: tier.is_featured === true || tier.is_featured === 1,
      trial_days: tier.trial_days,
      updated_at: tier.updated_at
    });
    
  } catch (error) {
    console.error('Tier update error:', error);
    return NextResponse.json(
      { error: 'Failed to update tier', message: error.message },
      { status: 500 }
    );
  }
}


