/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const body = await request.json();
    const { name, description, status, priority, visibility, color, icon, start_date, due_date, budget } = body;
    
    if (!name || !name.trim()) {
      return NextResponse.json({ error: 'Project name is required' }, { status: 400 });
    }
    
    // Get employee ID for current user
    const empQuery = `SELECT id FROM employees WHERE userid = ?`;
    const empResult = await db_query(db, empQuery, [user_id]);
    
    if (empResult.length === 0) {
      return NextResponse.json({ error: 'Employee profile required to create projects' }, { status: 403 });
    }
    
    const employeeId = empResult[0].id;
    
    // Generate unique slug
    const baseSlug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    let slug = baseSlug;
    let counter = 1;
    while (true) {
      const slugCheck = await db_query(db, `SELECT id FROM projects WHERE slug = ?`, [slug]);
      if (slugCheck.length === 0) break;
      slug = `${baseSlug}-${counter}`;
      counter++;
    }
    
    const projectId = crypto.randomUUID();
    
    const insertQuery = `
      INSERT INTO projects (
        id, userid, name, slug, description, owner_id, status, priority, visibility,
        color, icon, start_date, due_date, budget
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      RETURNING *
    `;
    
    const params = [
      projectId,
      user_id,
      name.trim(),
      slug,
      description || null,
      employeeId,
      status || 'planning',
      priority || 'medium',
      visibility || 'private',
      color || '#3B82F6',
      icon || null,
      start_date || null,
      due_date || null,
      budget || null
    ];
    
    const result = await db_query(db, insertQuery, params);
    const project = result[0];
    
    // Add owner as project member
    const memberQuery = `
      INSERT INTO project_members (id, project_id, employee_id, role, invited_by)
      VALUES (?, ?, ?, 'owner', ?)
    `;
    await db_query(db, memberQuery, [crypto.randomUUID(), projectId, employeeId, employeeId]);
    
    return NextResponse.json({
      id: project.id,
      name: project.name,
      slug: project.slug,
      description: project.description,
      owner_id: project.owner_id,
      status: project.status,
      priority: project.priority,
      visibility: project.visibility,
      color: project.color,
      created_at: project.created_at
    }, { status: 201 });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to create project', message: error.message },
      { status: 500 }
    );
  }
}


