/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json({ error: 'Task ID is required' }, { status: 400 });
    }
    
    const query = `
      SELECT 
        t.*,
        a.id as assignee_id, a.first_name as assignee_first_name, a.last_name as assignee_last_name, 
        a.email as assignee_email, a.avatar_url as assignee_avatar,
        r.id as reporter_id, r.first_name as reporter_first_name, r.last_name as reporter_last_name,
        r.avatar_url as reporter_avatar
      FROM tasks t
      LEFT JOIN employees a ON t.assignee_id = a.id
      LEFT JOIN employees r ON t.reporter_id = r.id
      WHERE t.id = ?
    `;
    
    const result = await db_query(db, query, [id]);
    
    if (result.length === 0) {
      return NextResponse.json({ error: 'Task not found' }, { status: 404 });
    }
    
    const t = result[0];
    
    // Get subtask count
    const subtaskQuery = `SELECT COUNT(*) as count FROM tasks WHERE parent_task_id = ?`;
    const subtaskResult = await db_query(db, subtaskQuery, [id]);
    
    return NextResponse.json({
      data: {
        id: t.id,
        project_id: t.project_id,
        parent_task_id: t.parent_task_id,
        title: t.title,
        description: t.description,
        status: t.status,
        priority: t.priority,
        assignee: t.assignee_id ? {
          id: t.assignee_id,
          name: `${t.assignee_first_name} ${t.assignee_last_name}`,
          email: t.assignee_email,
          avatar_url: t.assignee_avatar
        } : null,
        reporter: t.reporter_id ? {
          id: t.reporter_id,
          name: `${t.reporter_first_name} ${t.reporter_last_name}`,
          avatar_url: t.reporter_avatar
        } : null,
        due_date: t.due_date,
        start_date: t.start_date,
        completed_at: t.completed_at,
        estimated_hours: t.estimated_hours ? parseFloat(t.estimated_hours) : null,
        actual_hours: parseFloat(t.actual_hours) || 0,
        position: parseInt(t.position) || 0,
        labels: t.labels || [],
        attachments: t.attachments || [],
        checklist: t.checklist || [],
        comment_count: parseInt(t.comment_count) || 0,
        subtask_count: parseInt(subtaskResult[0].count) || 0,
        metadata: t.metadata || {},
        created_at: t.created_at,
        updated_at: t.updated_at
      }
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to get task', message: error.message },
      { status: 500 }
    );
  }
}


