/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const body = await request.json();
    const { id, ...updates } = body;
    
    if (!id) {
      return NextResponse.json(
        { error: 'Employee ID is required' },
        { status: 400 }
      );
    }
    
    // Check if employee exists
    const checkQuery = `SELECT * FROM employees WHERE id = ?`;
    const existing = await db_query(db, checkQuery, [id]);
    
    if (existing.length === 0) {
      return NextResponse.json(
        { error: 'Employee not found' },
        { status: 404 }
      );
    }
    
    const employee = existing[0];
    
    // Check authorization - users can only update their own profile unless admin
    if (!is_admin && employee.userid !== user_id) {
      return NextResponse.json(
        { error: 'Not authorized to update this employee' },
        { status: 403 }
      );
    }
    
    // Build update fields
    const updateFields = [];
    const values = [];
    
    const allowedFields = [
      'first_name', 'last_name', 'phone', 'avatar_url', 'job_title',
      'department', 'manager_id', 'employment_type', 'status',
      'location', 'timezone', 'bio'
    ];
    
    // Admin-only fields
    const adminOnlyFields = ['job_title', 'department', 'manager_id', 'employment_type', 'status', 'hourly_rate'];
    
    for (const [key, value] of Object.entries(updates)) {
      if (!allowedFields.includes(key)) continue;
      if (adminOnlyFields.includes(key) && !is_admin) continue;
      
      updateFields.push(`${key} = ?`);
      values.push(value);
    }
    
    // Handle skills separately (JSON)
    if (updates.skills !== undefined) {
      updateFields.push('skills = ?');
      values.push(JSON.stringify(updates.skills));
    }
    
    if (updateFields.length === 0) {
      return NextResponse.json(
        { error: 'No valid fields to update' },
        { status: 400 }
      );
    }
    
    updateFields.push('updated_at = CURRENT_TIMESTAMP');
    values.push(id);
    
    const updateQuery = `
      UPDATE employees 
      SET ${updateFields.join(', ')}
      WHERE id = ?
      RETURNING *
    `;
    
    const result = await db_query(db, updateQuery, values);
    const emp = result[0];
    
    return NextResponse.json({
      data: {
        id: emp.id,
        userid: emp.userid,
        employee_number: emp.employee_number,
        first_name: emp.first_name,
        last_name: emp.last_name,
        full_name: `${emp.first_name} ${emp.last_name}`,
        email: emp.email,
        phone: emp.phone,
        avatar_url: emp.avatar_url,
        job_title: emp.job_title,
        department: emp.department,
        manager_id: emp.manager_id,
        employment_type: emp.employment_type,
        status: emp.status,
        location: emp.location,
        timezone: emp.timezone,
        skills: emp.skills || [],
        bio: emp.bio,
        created_at: emp.created_at,
        updated_at: emp.updated_at
      }
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to update employee', message: error.message },
      { status: 500 }
    );
  }
}


