/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
    }
    
    // Get project
    const projectQuery = `SELECT * FROM projects WHERE id = ?`;
    const projectResult = await db_query(db, projectQuery, [id]);
    
    if (projectResult.length === 0) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }
    
    const project = projectResult[0];
    
    // Check authorization
    const empQuery = `SELECT id FROM employees WHERE userid = ?`;
    const empResult = await db_query(db, empQuery, [user_id]);
    const employeeId = empResult.length > 0 ? empResult[0].id : null;
    
    if (!is_admin && project.owner_id !== employeeId) {
      return NextResponse.json({ error: 'Only project owner can delete' }, { status: 403 });
    }
    
    // Delete in order: comments, tasks, time_entries, invoices, members, project
    const taskIds = await db_query(db, `SELECT id FROM tasks WHERE project_id = ?`, [id]);
    
    if (taskIds.length > 0) {
      const taskIdList = taskIds.map(t => t.id);
      await db_query(db, `DELETE FROM task_comments WHERE task_id IN (${taskIdList.map(() => '?').join(',')})`, taskIdList);
    }
    
    await db_query(db, `DELETE FROM tasks WHERE project_id = ?`, [id]);
    await db_query(db, `DELETE FROM time_entries WHERE project_id = ?`, [id]);
    await db_query(db, `DELETE FROM invoices WHERE project_id = ?`, [id]);
    await db_query(db, `DELETE FROM project_members WHERE project_id = ?`, [id]);
    await db_query(db, `DELETE FROM projects WHERE id = ?`, [id]);
    
    return NextResponse.json({ success: true });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to delete project', message: error.message },
      { status: 500 }
    );
  }
}


