/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const task_id = searchParams.get('task_id');
    
    if (!task_id) {
      return NextResponse.json({ error: 'Task ID is required' }, { status: 400 });
    }
    
    const query = `
      SELECT 
        c.*,
        e.first_name, e.last_name, e.avatar_url, e.job_title
      FROM task_comments c
      LEFT JOIN employees e ON c.author_id = e.id
      WHERE c.task_id = ?
      ORDER BY c.created_at ASC
    `;
    
    const result = await db_query(db, query, [task_id]);
    
    const comments = result.map(c => ({
      id: c.id,
      task_id: c.task_id,
      author: {
        id: c.author_id,
        name: `${c.first_name} ${c.last_name}`,
        avatar_url: c.avatar_url,
        job_title: c.job_title
      },
      content: c.content,
      parent_comment_id: c.parent_comment_id,
      attachments: c.attachments || [],
      mentions: c.mentions || [],
      edited_at: c.edited_at,
      created_at: c.created_at
    }));
    
    return NextResponse.json({ data: comments });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to list comments', message: error.message },
      { status: 500 }
    );
  }
}


