/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  if (!is_admin) {
    return NextResponse.json(
      { error: 'Admin access required' },
      { status: 403 }
    );
  }
  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'Tier ID is required' },
        { status: 400 }
      );
    }
    
    // Check if tier exists
    const existingQuery = 'SELECT * FROM subscription_tiers WHERE id = ?';
    const existingResult = await db_query(db, existingQuery, [id]);
    
    if (existingResult.length === 0) {
      return NextResponse.json(
        { error: 'Tier not found' },
        { status: 404 }
      );
    }
    
    const tier = existingResult[0];
    
    // Check if any subscriptions are using this tier
    const subscriptionsQuery = 'SELECT COUNT(*) as count FROM subscriptions WHERE user_tier = ? OR tiersid = ?';
    const subscriptionsResult = await db_query(db, subscriptionsQuery, [tier.slug, id]);
    
    const subscriberCount = subscriptionsResult[0]?.count || 0;
    
    if (subscriberCount > 0) {
      return NextResponse.json(
        { 
          success: false,
          error: 'Cannot delete tier with active subscribers',
          message: `This tier has ${subscriberCount} subscriber(s). Please migrate them to a different tier before deleting.`
        },
        { status: 400 }
      );
    }
    
    // Delete the tier
    const deleteQuery = 'DELETE FROM subscription_tiers WHERE id = ?';
    await db_query(db, deleteQuery, [id]);
    
    return NextResponse.json({
      success: true,
      message: 'Tier deleted successfully',
      id: id
    });
    
  } catch (error) {
    console.error('Tier deletion error:', error);
    return NextResponse.json(
      { error: 'Failed to delete tier', message: error.message },
      { status: 500 }
    );
  }
}


