/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse request body
    const body = await request.json();
    const {
      userid, first_name, last_name, email, phone,
      date_of_birth, gender, company_name, vat_number,
      customer_type, preferred_language, preferred_currency,
      marketing_consent, newsletter_subscribed, notes, tags
    } = body;
    
    // Validate required fields
    if (!userid || !first_name || !last_name || !email) {
      return NextResponse.json(
        { error: 'User ID, first name, last name, and email are required' },
        { status: 400 }
      );
    }
    
    // Validate names are not empty
    if (!first_name.trim() || !last_name.trim()) {
      return NextResponse.json(
        { error: 'First name and last name cannot be empty' },
        { status: 400 }
      );
    }
    
    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      );
    }
    
    // Validate UUID format for userid
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(userid)) {
      return NextResponse.json(
        { error: 'Invalid user ID format' },
        { status: 400 }
      );
    }
    
    // Check if user exists
    const checkUserQuery = `
      SELECT id FROM users WHERE id = ?
    `;
    const userResult = await db_query(db, checkUserQuery, [userid]);
    
    if (userResult.length === 0) {
      return NextResponse.json(
        { error: 'User not found' },
        { status: 404 }
      );
    }
    
    // Check if customer already exists for this user
    const checkCustomerQuery = `
      SELECT id FROM customers WHERE userid = ?
    `;
    const existingCustomer = await db_query(db, checkCustomerQuery, [userid]);
    
    if (existingCustomer.length > 0) {
      return NextResponse.json(
        { error: 'Customer profile already exists for this user' },
        { status: 400 }
      );
    }
    
    // Check if email is unique
    const checkEmailQuery = `
      SELECT COUNT(*) as count 
      FROM customers 
      WHERE LOWER(email) = LOWER(?)
    `;
    const emailResult = await db_query(db, checkEmailQuery, [email.trim()]);
    
    if (emailResult[0].count > 0) {
      return NextResponse.json(
        { error: 'Email already exists' },
        { status: 400 }
      );
    }
    
    // Generate UUID for the new customer
    const customerId = crypto.randomUUID();
    
    // Create customer
    const createQuery = `
      INSERT INTO customers (
        id, userid, first_name, last_name, email, phone,
        date_of_birth, gender, company_name, vat_number,
        customer_type, preferred_language, preferred_currency,
        marketing_consent, newsletter_subscribed, notes, tags
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      RETURNING *
    `;
    
    const params = [
      customerId,
      userid,
      first_name.trim(),
      last_name.trim(),
      email.trim(),
      phone || null,
      date_of_birth || null,
      gender || null,
      company_name || null,
      vat_number || null,
      customer_type || 'individual',
      preferred_language || 'en',
      preferred_currency || 'USD',
      marketing_consent !== undefined ? marketing_consent : false,
      newsletter_subscribed !== undefined ? newsletter_subscribed : false,
      notes || null,
      JSON.stringify(tags || [])
    ];
    
    const result = await db_query(db, createQuery, params);
    const customer = result[0];
    
    // Format response
    const response = {
      id: customer.id,
      userid: customer.userid,
      first_name: customer.first_name,
      last_name: customer.last_name,
      email: customer.email,
      phone: customer.phone,
      date_of_birth: customer.date_of_birth,
      gender: customer.gender,
      company_name: customer.company_name,
      vat_number: customer.vat_number,
      customer_type: customer.customer_type,
      status: customer.status,
      loyalty_points: parseInt(customer.loyalty_points),
      loyalty_tier: customer.loyalty_tier,
      total_spent: parseFloat(customer.total_spent),
      total_orders: parseInt(customer.total_orders),
      preferred_language: customer.preferred_language,
      preferred_currency: customer.preferred_currency,
      marketing_consent: customer.marketing_consent,
      newsletter_subscribed: customer.newsletter_subscribed,
      notes: customer.notes,
      tags: customer.tags || [],
      metadata: customer.metadata || {},
      created_at: customer.created_at
    };
    
    return NextResponse.json(response, { status: 201 });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to create customer', message: error.message },
      { status: 500 }
    );
  }
}


