/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    const userId = searchParams.get('userid');
    
    if (!id && !userId) {
      return NextResponse.json(
        { error: 'Either id or userid is required' },
        { status: 400 }
      );
    }
    
    let query;
    let params;
    
    if (id) {
      query = `SELECT * FROM employees WHERE id = ?`;
      params = [id];
    } else {
      query = `SELECT * FROM employees WHERE userid = ?`;
      params = [userId];
    }
    
    const result = await db_query(db, query, params);
    
    if (result.length === 0) {
      return NextResponse.json(
        { error: 'Employee not found' },
        { status: 404 }
      );
    }
    
    const emp = result[0];
    
    return NextResponse.json({
      data: {
        id: emp.id,
        userid: emp.userid,
        employee_number: emp.employee_number,
        first_name: emp.first_name,
        last_name: emp.last_name,
        full_name: `${emp.first_name} ${emp.last_name}`,
        email: emp.email,
        phone: emp.phone,
        avatar_url: emp.avatar_url,
        job_title: emp.job_title,
        department: emp.department,
        manager_id: emp.manager_id,
        hire_date: emp.hire_date,
        employment_type: emp.employment_type,
        status: emp.status,
        location: emp.location,
        timezone: emp.timezone,
        hourly_rate: emp.hourly_rate ? parseFloat(emp.hourly_rate) : null,
        skills: emp.skills || [],
        bio: emp.bio,
        social_links: emp.social_links || {},
        settings: emp.settings || {},
        created_at: emp.created_at,
        updated_at: emp.updated_at
      }
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to get employee', message: error.message },
      { status: 500 }
    );
  }
}


