/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    const slug = searchParams.get('slug');
    
    if (!id && !slug) {
      return NextResponse.json({ error: 'Either id or slug is required' }, { status: 400 });
    }
    
    let query = `SELECT * FROM projects WHERE ${id ? 'id' : 'slug'} = ?`;
    const result = await db_query(db, query, [id || slug]);
    
    if (result.length === 0) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }
    
    const project = result[0];
    
    // Check access - get employee ID
    const empQuery = `SELECT id FROM employees WHERE userid = ?`;
    const empResult = await db_query(db, empQuery, [user_id]);
    const employeeId = empResult.length > 0 ? empResult[0].id : null;
    
    if (!is_admin && employeeId) {
      const accessQuery = `
        SELECT 1 FROM project_members 
        WHERE project_id = ? AND employee_id = ?
        UNION
        SELECT 1 FROM projects WHERE id = ? AND owner_id = ?
      `;
      const accessResult = await db_query(db, accessQuery, [project.id, employeeId, project.id, employeeId]);
      
      if (accessResult.length === 0 && project.visibility !== 'public') {
        return NextResponse.json({ error: 'Access denied' }, { status: 403 });
      }
    }
    
    // Get member count
    const memberCountQuery = `SELECT COUNT(*) as count FROM project_members WHERE project_id = ?`;
    const memberCount = await db_query(db, memberCountQuery, [project.id]);
    
    // Get owner details
    const ownerQuery = `SELECT id, first_name, last_name, email, avatar_url, job_title FROM employees WHERE id = ?`;
    const ownerResult = await db_query(db, ownerQuery, [project.owner_id]);
    const owner = ownerResult.length > 0 ? ownerResult[0] : null;
    
    return NextResponse.json({
      data: {
        id: project.id,
        name: project.name,
        slug: project.slug,
        description: project.description,
        owner_id: project.owner_id,
        owner: owner ? {
          id: owner.id,
          name: `${owner.first_name} ${owner.last_name}`,
          email: owner.email,
          avatar_url: owner.avatar_url,
          job_title: owner.job_title
        } : null,
        status: project.status,
        priority: project.priority,
        visibility: project.visibility,
        color: project.color,
        icon: project.icon,
        start_date: project.start_date,
        due_date: project.due_date,
        completed_at: project.completed_at,
        budget: project.budget ? parseFloat(project.budget) : null,
        budget_spent: parseFloat(project.budget_spent) || 0,
        progress: parseInt(project.progress) || 0,
        task_count: parseInt(project.task_count) || 0,
        completed_task_count: parseInt(project.completed_task_count) || 0,
        member_count: parseInt(memberCount[0].count) || 0,
        settings: project.settings || {},
        metadata: project.metadata || {},
        created_at: project.created_at,
        updated_at: project.updated_at
      }
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to get project', message: error.message },
      { status: 500 }
    );
  }
}


