/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const body = await request.json();
    const { id, ...updates } = body;
    
    if (!id) {
      return NextResponse.json({ error: 'Task ID is required' }, { status: 400 });
    }
    
    // Get existing task
    const taskQuery = `SELECT * FROM tasks WHERE id = ?`;
    const taskResult = await db_query(db, taskQuery, [id]);
    
    if (taskResult.length === 0) {
      return NextResponse.json({ error: 'Task not found' }, { status: 404 });
    }
    
    const task = taskResult[0];
    const wasCompleted = task.status === 'done';
    const willBeCompleted = updates.status === 'done';
    
    const updateFields = [];
    const values = [];
    
    const allowedFields = ['title', 'description', 'status', 'priority', 'assignee_id', 'due_date', 'start_date', 'estimated_hours', 'actual_hours', 'position'];
    
    for (const [key, value] of Object.entries(updates)) {
      if (!allowedFields.includes(key)) continue;
      updateFields.push(`${key} = ?`);
      values.push(value);
    }
    
    // Handle arrays
    if (updates.labels !== undefined) {
      updateFields.push('labels = ?');
      values.push(JSON.stringify(updates.labels));
    }
    
    if (updates.checklist !== undefined) {
      updateFields.push('checklist = ?');
      values.push(JSON.stringify(updates.checklist));
    }
    
    // Handle completion
    if (!wasCompleted && willBeCompleted) {
      updateFields.push('completed_at = CURRENT_TIMESTAMP');
    } else if (wasCompleted && updates.status && updates.status !== 'done') {
      updateFields.push('completed_at = NULL');
    }
    
    if (updateFields.length === 0) {
      return NextResponse.json({ error: 'No valid fields to update' }, { status: 400 });
    }
    
    updateFields.push('updated_at = CURRENT_TIMESTAMP');
    values.push(id);
    
    const updateQuery = `UPDATE tasks SET ${updateFields.join(', ')} WHERE id = ? RETURNING *`;
    const result = await db_query(db, updateQuery, values);
    const updated = result[0];
    
    // Update project completed count and progress
    if (wasCompleted !== willBeCompleted) {
      const delta = willBeCompleted ? 1 : -1;
      
      await db_query(db, `
        UPDATE projects 
        SET completed_task_count = completed_task_count + ?,
            progress = CASE WHEN task_count > 0 THEN ((completed_task_count + ?) * 100 / task_count) ELSE 0 END,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
      `, [delta, delta, task.project_id]);
    }
    
    return NextResponse.json({
      data: {
        id: updated.id,
        project_id: updated.project_id,
        title: updated.title,
        description: updated.description,
        status: updated.status,
        priority: updated.priority,
        assignee_id: updated.assignee_id,
        due_date: updated.due_date,
        completed_at: updated.completed_at,
        position: parseInt(updated.position) || 0,
        labels: updated.labels || [],
        checklist: updated.checklist || [],
        updated_at: updated.updated_at
      }
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to update task', message: error.message },
      { status: 500 }
    );
  }
}


