/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Get customer_id for the authenticated user
    const customerResult = await db_query(db, 'SELECT id FROM customers WHERE userid = ?', [user_id]);
    if (customerResult.length === 0) {
      return NextResponse.json({ error: 'Customer profile not found' }, { status: 404 });
    }
    const customer_id = customerResult[0].id;
    
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json({ error: 'Time entry ID is required' }, { status: 400 });
    }
    
    // Check if entry exists and belongs to customer
    const checkQuery = `SELECT customer_id FROM time_entries WHERE id = ?`;
    const checkResult = await db_query(db, checkQuery, [id]);
    
    if (checkResult.length === 0) {
      return NextResponse.json({ error: 'Time entry not found' }, { status: 404 });
    }
    
    if (checkResult[0].customer_id !== customer_id && !is_admin) {
      return NextResponse.json({ error: 'Not authorized to delete this entry' }, { status: 403 });
    }
    
    const deleteQuery = `DELETE FROM time_entries WHERE id = ?`;
    await db_query(db, deleteQuery, [id]);
    
    return NextResponse.json({ success: true });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to delete time entry', message: error.message },
      { status: 500 }
    );
  }
}


