/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  if (!user_id) {
    return NextResponse.json(
      { error: 'Authentication required' },
      { status: 401 }
    );
  }
  
  try {
    const { price_id, trial_days } = await request.json();
    
    // Validate input
    if (!price_id) {
      return NextResponse.json(
        { error: 'Price ID is required' },
        { status: 400 }
      );
    }
    
    // Get customer ID for the user
    const customerQuery = 'SELECT id, email, first_name, last_name FROM customers WHERE userid = ?';
    const customerResult = await db_query(db, customerQuery, [user_id]);
    
    if (customerResult.length === 0) {
      return NextResponse.json(
        { error: 'Customer profile not found. Please complete your profile first.' },
        { status: 404 }
      );
    }
    
    const customer = customerResult[0];
    const customersId = customer.id;
    
    // Get Stripe Connect account ID
    const stripeConnectAccountId = await window.getKey('NEXT_PUBLIC_STRIPE_CONNECT_ACCOUNT_ID');
    if (!stripeConnectAccountId) {
      return NextResponse.json(
        { 
          error: 'Stripe Connect not configured',
          requiresSetup: true,
          message: 'Please go to the Settings tab in Sitepaige to set up Stripe Connect'
        },
        { status: 400 }
      );
    }
    
    // Check for existing subscription
    const existingSubQuery = 'SELECT id, stripe_subscription_id, status FROM subscriptions WHERE customersid = ?';
    const existingSubResult = await db_query(db, existingSubQuery, [customersId]);
    
    let subscriptionId;
    
    if (existingSubResult.length === 0) {
      // Create new subscription record with pending status
      const createSubQuery = `
        INSERT INTO subscriptions (customersid, status, user_tier, price_id)
        VALUES (?, 'pending', 'free', ?)
      `;
      const subResult = await db_query(db, createSubQuery, [customersId, price_id]);
      subscriptionId = subResult.insertId || subResult.lastID;
    } else {
      subscriptionId = existingSubResult[0].id;
      // Update the price_id if changing plans
      const updateSubQuery = 'UPDATE subscriptions SET price_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?';
      await db_query(db, updateSubQuery, [price_id, subscriptionId]);
    }
    
    // Build Stripe checkout session parameters
    const stripeParams = new URLSearchParams();
    stripeParams.append('payment_method_types[]', 'card');
    stripeParams.append('mode', 'subscription');
    stripeParams.append('customer_email', customer.email);
    stripeParams.append('success_url', `${process.env.NEXT_PUBLIC_APP_URL}/subscription-success?session_id={CHECKOUT_SESSION_ID}`);
    stripeParams.append('cancel_url', `${process.env.NEXT_PUBLIC_APP_URL}/pricing`);
    
    // Add subscription line item
    stripeParams.append('line_items[0][price]', price_id);
    stripeParams.append('line_items[0][quantity]', '1');
    
    // Add trial period if specified
    if (trial_days && trial_days > 0) {
      stripeParams.append('subscription_data[trial_period_days]', trial_days.toString());
    }
    
    // Add metadata
    stripeParams.append('metadata[subscription_id]', subscriptionId.toString());
    stripeParams.append('metadata[customer_id]', customersId);
    stripeParams.append('metadata[user_id]', user_id);
    
    // Subscription-specific data
    stripeParams.append('subscription_data[metadata][subscription_id]', subscriptionId.toString());
    stripeParams.append('subscription_data[metadata][customer_id]', customersId);
    stripeParams.append('subscription_data[metadata][user_id]', user_id);
    
    // Allow promotion codes
    stripeParams.append('allow_promotion_codes', 'true');
    
    // Create Stripe checkout session
    const stripeResponse = await fetch('https://api.stripe.com/v1/checkout/sessions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.STRIPE_SECRET_KEY}`,
        'Stripe-Account': stripeConnectAccountId,
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: stripeParams.toString()
    });
    
    if (!stripeResponse.ok) {
      const errorData = await stripeResponse.json();
      console.error('Stripe error:', errorData);
      throw new Error(errorData.error?.message || 'Failed to create checkout session');
    }
    
    const session = await stripeResponse.json();
    
    return NextResponse.json({
      checkoutUrl: session.url,
      sessionId: session.id
    });
    
  } catch (error) {
    console.error('Subscription creation error:', error);
    return NextResponse.json(
      { error: 'Failed to create subscription', message: error.message },
      { status: 500 }
    );
  }
}


