/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Get customer_id for the authenticated user
    const customerResult = await db_query(db, 'SELECT id FROM customers WHERE userid = ?', [user_id]);
    if (customerResult.length === 0) {
      return NextResponse.json({ error: 'Customer profile not found' }, { status: 404 });
    }
    const customer_id = customerResult[0].id;
    
    const { searchParams } = new URL(request.url);
    const project_id = searchParams.get('project_id');
    const task_id = searchParams.get('task_id');
    const start_date = searchParams.get('start_date');
    const end_date = searchParams.get('end_date');
    const is_billable = searchParams.get('is_billable');
    const search = searchParams.get('search');
    const page = parseInt(searchParams.get('page')) || 1;
    const limit = parseInt(searchParams.get('limit')) || 20;
    const offset = (page - 1) * limit;
    
    let conditions = ['te.customer_id = ?'];
    let params = [customer_id];
    
    if (project_id) {
      conditions.push('te.project_id = ?');
      params.push(project_id);
    }
    
    if (task_id) {
      conditions.push('te.task_id = ?');
      params.push(task_id);
    }
    
    if (start_date) {
      conditions.push('te.start_time >= ?');
      params.push(start_date);
    }
    
    if (end_date) {
      conditions.push('te.start_time <= ?');
      params.push(end_date + ' 23:59:59');
    }
    
    if (is_billable !== null && is_billable !== undefined && is_billable !== '') {
      conditions.push('te.is_billable = ?');
      params.push(is_billable === 'true');
    }
    
    if (search) {
      conditions.push('te.description ILIKE ?');
      params.push(`%${search}%`);
    }
    
    const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
    
    // Count total
    const countQuery = `SELECT COUNT(*) as total FROM time_entries te ${whereClause}`;
    const countResult = await db_query(db, countQuery, params);
    const total = parseInt(countResult[0].total) || 0;
    
    // Fetch entries with optional project and task details
    const query = `
      SELECT 
        te.*,
        p.name as project_name,
        p.color as project_color,
        t.title as task_title
      FROM time_entries te
      LEFT JOIN projects p ON te.project_id = p.id
      LEFT JOIN tasks t ON te.task_id = t.id
      ${whereClause}
      ORDER BY te.start_time DESC
      LIMIT ? OFFSET ?
    `;
    
    const result = await db_query(db, query, [...params, limit, offset]);
    
    const entries = result.map(row => ({
      id: row.id,
      customer_id: row.customer_id,
      project_id: row.project_id,
      task_id: row.task_id,
      description: row.description,
      start_time: row.start_time,
      end_time: row.end_time,
      duration_minutes: parseInt(row.duration_minutes) || 0,
      is_running: row.is_running,
      is_billable: row.is_billable,
      hourly_rate: parseFloat(row.hourly_rate) || null,
      tags: row.tags || [],
      project: row.project_id ? { id: row.project_id, name: row.project_name, color: row.project_color } : null,
      task: row.task_id ? { id: row.task_id, title: row.task_title } : null,
      created_at: row.created_at,
      updated_at: row.updated_at
    }));
    
    return NextResponse.json({
      data: entries,
      total,
      page,
      limit
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to fetch time entries', message: error.message },
      { status: 500 }
    );
  }
}


