/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const body = await request.json();
    const { id, ...updates } = body;
    
    if (!id) {
      return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
    }
    
    // Get project
    const projectQuery = `SELECT * FROM projects WHERE id = ?`;
    const projectResult = await db_query(db, projectQuery, [id]);
    
    if (projectResult.length === 0) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }
    
    const project = projectResult[0];
    
    // Check authorization
    const empQuery = `SELECT id FROM employees WHERE userid = ?`;
    const empResult = await db_query(db, empQuery, [user_id]);
    const employeeId = empResult.length > 0 ? empResult[0].id : null;
    
    if (!is_admin && project.owner_id !== employeeId) {
      // Check if admin member
      const memberQuery = `SELECT role FROM project_members WHERE project_id = ? AND employee_id = ? AND role IN ('owner', 'admin')`;
      const memberResult = await db_query(db, memberQuery, [id, employeeId]);
      if (memberResult.length === 0) {
        return NextResponse.json({ error: 'Not authorized to update this project' }, { status: 403 });
      }
    }
    
    const updateFields = [];
    const values = [];
    
    const allowedFields = ['name', 'description', 'status', 'priority', 'visibility', 'color', 'icon', 'start_date', 'due_date', 'budget', 'settings', 'metadata'];
    
    for (const [key, value] of Object.entries(updates)) {
      if (!allowedFields.includes(key)) continue;
      updateFields.push(`${key} = ?`);
      values.push(value);
    }
    
    // Handle status change to completed
    if (updates.status === 'completed' && project.status !== 'completed') {
      updateFields.push('completed_at = CURRENT_TIMESTAMP');
    } else if (updates.status && updates.status !== 'completed' && project.status === 'completed') {
      updateFields.push('completed_at = NULL');
    }
    
    // Update slug if name changes
    if (updates.name) {
      const baseSlug = updates.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
      let slug = baseSlug;
      let counter = 1;
      while (true) {
        const slugCheck = await db_query(db, `SELECT id FROM projects WHERE slug = ? AND id != ?`, [slug, id]);
        if (slugCheck.length === 0) break;
        slug = `${baseSlug}-${counter}`;
        counter++;
      }
      updateFields.push('slug = ?');
      values.push(slug);
    }
    
    if (updateFields.length === 0) {
      return NextResponse.json({ error: 'No valid fields to update' }, { status: 400 });
    }
    
    updateFields.push('updated_at = CURRENT_TIMESTAMP');
    values.push(id);
    
    const updateQuery = `UPDATE projects SET ${updateFields.join(', ')} WHERE id = ? RETURNING *`;
    const result = await db_query(db, updateQuery, values);
    const updated = result[0];
    
    return NextResponse.json({
      data: {
        id: updated.id,
        name: updated.name,
        slug: updated.slug,
        description: updated.description,
        owner_id: updated.owner_id,
        status: updated.status,
        priority: updated.priority,
        visibility: updated.visibility,
        color: updated.color,
        icon: updated.icon,
        start_date: updated.start_date,
        due_date: updated.due_date,
        completed_at: updated.completed_at,
        budget: updated.budget ? parseFloat(updated.budget) : null,
        budget_spent: updated.budget_spent ? parseFloat(updated.budget_spent) : null,
        progress: parseInt(updated.progress) || 0,
        task_count: parseInt(updated.task_count) || 0,
        completed_task_count: parseInt(updated.completed_task_count) || 0,
        settings: updated.settings,
        metadata: updated.metadata,
        created_at: updated.created_at,
        updated_at: updated.updated_at
      }
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to update project', message: error.message },
      { status: 500 }
    );
  }
}


