/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Get customer ID for the current user
    const customerResult = await db_query(
      db,
      'SELECT id FROM customers WHERE userid = ?',
      [user_id]
    );
    
    if (!customerResult || customerResult.length === 0) {
      // No customer record found, return empty array
      return NextResponse.json([]);
    }
    
    const customerId = customerResult[0].id;
    
    // Get SaaS orders for this customer
    const orders = await db_query(
      db,
      `SELECT * FROM saas_orders 
       WHERE customersid = ? 
       ORDER BY created_at DESC`,
      [customerId]
    );
    
    // Parse any JSON fields and format response
    const formattedOrders = orders.map(order => ({
      ...order,
      metadata: typeof order.metadata === 'string' ? JSON.parse(order.metadata) : (order.metadata || {}),
      amount: parseFloat(order.amount) || 0
    }));
    
    return NextResponse.json(formattedOrders);
    
  } catch (error) {
    console.error('SaaS orders list error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch orders', message: error.message },
      { status: 500 }
    );
  }
}


