/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function DELETE(request, { params }) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Get customer ID from query parameter
    const customerId = params.id;
    
    if (!customerId) {
      return NextResponse.json(
        { error: 'Customer ID is required' },
        { status: 400 }
      );
    }
    
    // Validate UUID format
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(customerId)) {
      return NextResponse.json(
        { error: 'Invalid customer ID format' },
        { status: 400 }
      );
    }
    
    // Soft delete by setting status to 'deleted'
    const deleteQuery = `
      UPDATE customers 
      SET status = 'deleted', 
          updated_at = CURRENT_TIMESTAMP 
      WHERE id = ? 
      RETURNING id, status
    `;
    
    const result = await db_query(db, deleteQuery, [customerId]);
    
    if (result.length === 0) {
      return NextResponse.json(
        { error: 'Customer not found' },
        { status: 404 }
      );
    }
    
    return NextResponse.json({
      success: true,
      message: 'Customer deleted successfully'
    });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to delete customer', message: error.message },
      { status: 500 }
    );
  }
}


