/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Get customer_id for the authenticated user
    const customerResult = await db_query(db, 'SELECT id FROM customers WHERE userid = ?', [user_id]);
    if (customerResult.length === 0) {
      return NextResponse.json({ error: 'Customer profile not found' }, { status: 404 });
    }
    const customer_id = customerResult[0].id;
    
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json(
        { error: 'Invoice ID is required' },
        { status: 400 }
      );
    }
    
    const query = `
      SELECT 
        i.*,
        c.first_name as customer_first_name,
        c.last_name as customer_last_name,
        c.email as customer_email,
        c.phone as customer_phone
      FROM invoices i
      LEFT JOIN customers c ON i.customer_id = c.id
      WHERE i.id = ? AND i.customer_id = ?
    `;
    
    const result = await db_query(db, query, [id, customer_id]);
    
    if (result.length === 0) {
      return NextResponse.json(
        { error: 'Invoice not found' },
        { status: 404 }
      );
    }
    
    const row = result[0];
    
    // Fetch associated time entries if any
    let timeEntries = [];
    const timeEntryIds = row.time_entry_ids || [];
    if (timeEntryIds.length > 0) {
      const placeholders = timeEntryIds.map(() => '?').join(',');
      const timeEntriesQuery = `
        SELECT 
          te.id,
          te.project_id,
          te.task_id,
          te.description,
          te.start_time,
          te.end_time,
          te.duration_minutes,
          te.is_billable,
          te.hourly_rate,
          te.tags,
          p.name as project_name,
          t.title as task_title
        FROM time_entries te
        LEFT JOIN projects p ON te.project_id = p.id
        LEFT JOIN tasks t ON te.task_id = t.id
        WHERE te.id IN (${placeholders})
      `;
      const timeEntriesResult = await db_query(db, timeEntriesQuery, timeEntryIds);
      timeEntries = timeEntriesResult.map(te => ({
        id: te.id,
        project_id: te.project_id,
        project_name: te.project_name,
        task_id: te.task_id,
        task_title: te.task_title,
        description: te.description,
        start_time: te.start_time,
        end_time: te.end_time,
        duration_minutes: te.duration_minutes,
        is_billable: te.is_billable,
        hourly_rate: parseFloat(te.hourly_rate) || 0,
        tags: te.tags || []
      }));
    }
    
    const invoice = {
      id: row.id,
      customer_id: row.customer_id,
      invoice_number: row.invoice_number,
      status: row.status,
      issue_date: row.issue_date,
      due_date: row.due_date,
      client_name: row.client_name,
      client_email: row.client_email,
      client_address: row.client_address,
      line_items: row.line_items || [],
      subtotal: parseFloat(row.subtotal) || 0,
      tax_rate: parseFloat(row.tax_rate) || 0,
      tax_amount: parseFloat(row.tax_amount) || 0,
      discount_amount: parseFloat(row.discount_amount) || 0,
      total: parseFloat(row.total) || 0,
      amount_paid: parseFloat(row.amount_paid) || 0,
      currency: row.currency,
      notes: row.notes,
      payment_terms: row.payment_terms,
      project_id: row.project_id,
      time_entry_ids: row.time_entry_ids || [],
      time_entries: timeEntries,
      paid_at: row.paid_at,
      sent_at: row.sent_at,
      customer: row.customer_id ? { 
        id: row.customer_id, 
        first_name: row.customer_first_name,
        last_name: row.customer_last_name,
        email: row.customer_email,
        phone: row.customer_phone
      } : null,
      created_at: row.created_at,
      updated_at: row.updated_at
    };
    
    return NextResponse.json(invoice);
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to fetch invoice', message: error.message },
      { status: 500 }
    );
  }
}


