/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const { searchParams } = new URL(request.url);
    const project_id = searchParams.get('project_id');
    
    if (!project_id) {
      return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
    }
    
    const query = `
      SELECT 
        pm.*,
        e.first_name, e.last_name, e.email, e.avatar_url, e.job_title, e.department
      FROM project_members pm
      LEFT JOIN employees e ON pm.employee_id = e.id
      WHERE pm.project_id = ?
      ORDER BY 
        CASE pm.role 
          WHEN 'owner' THEN 1 
          WHEN 'admin' THEN 2 
          WHEN 'member' THEN 3 
          ELSE 4 
        END,
        e.last_name ASC
    `;
    
    const result = await db_query(db, query, [project_id]);
    
    const members = result.map(m => ({
      id: m.id,
      project_id: m.project_id,
      employee_id: m.employee_id,
      role: m.role,
      employee: {
        id: m.employee_id,
        name: `${m.first_name} ${m.last_name}`,
        email: m.email,
        avatar_url: m.avatar_url,
        job_title: m.job_title,
        department: m.department
      },
      joined_at: m.joined_at,
      notifications_enabled: m.notifications_enabled
    }));
    
    return NextResponse.json({ data: members });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to list project members', message: error.message },
      { status: 500 }
    );
  }
}


