/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const body = await request.json();
    const { project_id, title, description, status, priority, assignee_id, parent_task_id, due_date, start_date, estimated_hours, labels } = body;
    
    if (!project_id || !title || !title.trim()) {
      return NextResponse.json({ error: 'Project ID and title are required' }, { status: 400 });
    }
    
    // Get reporter employee ID
    const empQuery = `SELECT id FROM employees WHERE userid = ?`;
    const empResult = await db_query(db, empQuery, [user_id]);
    const reporterId = empResult.length > 0 ? empResult[0].id : null;
    
    // Get max position for this status in project
    const positionQuery = `
      SELECT COALESCE(MAX(position), 0) + 1 as next_pos 
      FROM tasks 
      WHERE project_id = ? AND status = ?
    `;
    const posResult = await db_query(db, positionQuery, [project_id, status || 'todo']);
    const position = parseInt(posResult[0].next_pos) || 0;
    
    const taskId = crypto.randomUUID();
    
    const insertQuery = `
      INSERT INTO tasks (
        id, project_id, parent_task_id, title, description, status, priority,
        assignee_id, reporter_id, due_date, start_date, estimated_hours, position, labels
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      RETURNING *
    `;
    
    const params = [
      taskId,
      project_id,
      parent_task_id || null,
      title.trim(),
      description || null,
      status || 'todo',
      priority || 'medium',
      assignee_id || null,
      reporterId,
      due_date || null,
      start_date || null,
      estimated_hours || null,
      position,
      JSON.stringify(labels || [])
    ];
    
    const result = await db_query(db, insertQuery, params);
    const task = result[0];
    
    // Update project task count
    await db_query(db, `UPDATE projects SET task_count = task_count + 1, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND userid = ?`, [project_id, user_id]);
    
    return NextResponse.json({
      id: task.id,
      project_id: task.project_id,
      title: task.title,
      status: task.status,
      priority: task.priority,
      position: parseInt(task.position) || 0,
      created_at: task.created_at
    }, { status: 201 });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to create task', message: error.message },
      { status: 500 }
    );
  }
}


