/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    const body = await request.json();
    const {
      userid: targetUserId, first_name, last_name, email, phone,
      avatar_url, job_title, department, manager_id, hire_date,
      employment_type, location, timezone, hourly_rate, skills, bio
    } = body;
    
    // Validate required fields
    if (!targetUserId || !first_name || !last_name || !email) {
      return NextResponse.json(
        { error: 'userid, first name, last name, and email are required' },
        { status: 400 }
      );
    }
    
    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      );
    }
    
    // Check if employee already exists for this user
    const checkQuery = `SELECT id FROM employees WHERE userid = ?`;
    const existing = await db_query(db, checkQuery, [targetUserId]);
    
    if (existing.length > 0) {
      return NextResponse.json(
        { error: 'Employee profile already exists for this user' },
        { status: 400 }
      );
    }
    
    // Check email uniqueness
    const checkEmailQuery = `SELECT id FROM employees WHERE LOWER(email) = LOWER(?)`;
    const emailExists = await db_query(db, checkEmailQuery, [email.trim()]);
    
    if (emailExists.length > 0) {
      return NextResponse.json(
        { error: 'Email already exists' },
        { status: 400 }
      );
    }
    
    // Generate employee number
    const countQuery = `SELECT COUNT(*) as count FROM employees`;
    const countResult = await db_query(db, countQuery, []);
    const empNumber = `EMP${String(parseInt(countResult[0].count) + 1).padStart(5, '0')}`;
    
    const employeeId = crypto.randomUUID();
    
    const insertQuery = `
      INSERT INTO employees (
        id, userid, employee_number, first_name, last_name, email, phone,
        avatar_url, job_title, department, manager_id, hire_date,
        employment_type, location, timezone, hourly_rate, skills, bio
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      RETURNING *
    `;
    
    const params = [
      employeeId,
      targetUserId,
      empNumber,
      first_name.trim(),
      last_name.trim(),
      email.trim(),
      phone || null,
      avatar_url || null,
      job_title || null,
      department || null,
      manager_id || null,
      hire_date || null,
      employment_type || 'full_time',
      location || null,
      timezone || 'UTC',
      hourly_rate || null,
      JSON.stringify(skills || []),
      bio || null
    ];
    
    const result = await db_query(db, insertQuery, params);
    const emp = result[0];
    
    return NextResponse.json({
      id: emp.id,
      userid: emp.userid,
      employee_number: emp.employee_number,
      first_name: emp.first_name,
      last_name: emp.last_name,
      full_name: `${emp.first_name} ${emp.last_name}`,
      email: emp.email,
      phone: emp.phone,
      job_title: emp.job_title,
      department: emp.department,
      status: emp.status,
      created_at: emp.created_at
    }, { status: 201 });
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to create employee', message: error.message },
      { status: 500 }
    );
  }
}


